prime: prime.c
	gcc prime.c -o prime -lpthread -lm
pi: pi.c
	gcc pi.c -o pi -lpthread -lm
numbers: numbers.c
	gcc numbers.c -o numbers -lpthread
fibonacci: fibonacci.c
	gcc fibonacci.c -o fibonacci -lpthread
pid: pid.c
	gcc pid.c -o pid -lpthread
clean:
	rm prime numbers pi fibonacci pid
